{"@t":"2020-03-26T09:32:36.3234819Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":18548,"ProcessName":"iisexpress","ThreadId":201,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-26T09:37:38.3283459Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":18548,"ProcessName":"iisexpress","ThreadId":170,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-26T09:42:40.3404522Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":18548,"ProcessName":"iisexpress","ThreadId":215,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-26T09:47:42.3736388Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":18548,"ProcessName":"iisexpress","ThreadId":112,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-26T09:52:44.3873673Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":18548,"ProcessName":"iisexpress","ThreadId":185,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-26T09:57:46.4036135Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":18548,"ProcessName":"iisexpress","ThreadId":220,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-26T10:02:48.4227453Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":18548,"ProcessName":"iisexpress","ThreadId":136,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-26T10:07:50.4396479Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":18548,"ProcessName":"iisexpress","ThreadId":122,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-26T10:09:12.0277388Z","@mt":"Login attempt succeeded for username {Username} from IP address {IpAddress}","Username":"Dimitar-Krastev","IpAddress":"::1","SourceContext":"Umbraco.Core.Security.UmbracoMembershipProviderBase","ProcessId":18548,"ProcessName":"iisexpress","ThreadId":30,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpSessionId":"wjnqaydfy5gs0mdlgvb3eqft","HttpRequestNumber":15,"HttpRequestId":"04cecae3-ac24-40ba-834e-0a63561bd919"}
{"@t":"2020-03-26T10:09:24.7710481Z","@mt":"Login attempt succeeded for username {Username} from IP address {IpAddress}","Username":"Ivan-Ivanov","IpAddress":"::1","SourceContext":"Umbraco.Core.Security.UmbracoMembershipProviderBase","ProcessId":18548,"ProcessName":"iisexpress","ThreadId":225,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpSessionId":"wjnqaydfy5gs0mdlgvb3eqft","HttpRequestNumber":16,"HttpRequestId":"71c1737a-daa7-4c38-8cfc-aa803de78e6d"}
